# No fancyness - we can use the new build infrastructure
sudo: false

language: java

jdk:
  - openjdk17

install: mvn --settings .travis.settings.xml clean install -DskipTests=true -Dmaven.javadoc.skip=true --batch-mode --show-version

before_script:
  - pip install codecov-cli

script:
  - mvn --settings .travis.settings.xml --batch-mode clean verify

after_success:
  - codecov

deploy:
  # deploy develop to Maven Central
  - provider: script
    script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy"
    on:
      branch: develop
