# No fancyness - we can use the new build infrastructure
sudo: false

language: java

jdk:
  - openjdk17

install: mvn --settings .travis.settings.xml clean install -DskipTests=true -Dmaven.javadoc.skip=true --batch-mode --show-version

before_script:
  - pip install codecov-cli

script:
  - mvn --settings .travis.settings.xml --batch-mode clean verify

deploy:
  # deploy develop to Maven Central
  - provider: script
    skip_cleanup: true
    script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn --batch-mode release:prepare && mvn --batch-mode release:perform && mvn deploy"
    on:
      branch: master
